### ISSUE TITLE
Error when using IPv6 address.

### ISSUE THREAD

**Issue by jeandudey** [AlCalzone/node-coap-client#253]
Hi!

I've been using your code to connect to a CoAP server, however, it fails when using IPv6 addresses directly, e.g:

```js
#!/usr/bin/env node

const coap = require("node-coap-client").CoapClient;

coap
    .request("coap://[2001:db8::1]:5683/system/info", "get")
    .then((response) => {
        console.log(result);
    })
    .catch((err) => {
        console.log(err);
    });
```

With the following output:

```
nts.js:292
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND [2001:db8::1]
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
Emitted 'error' event on SocketWrapper instance at:
    at Socket.<anonymous> (/xxx/coap/node_modules/node-coap-client/build/lib/SocketWrapper.js:15:18)
    at Socket.emit (events.js:315:20)
    at dgram.js:652:33
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '[2001:db8::1]'
}
```

It seems the IPv6 part isn't parsed correctly and `dgram` interprets it as a domain

**Comment by AlCalzone** [comment]
Fixed in v1.0.8. For the `coaps://` protocol, `udp6` was used for IPv6 destinations, but not for the `coap://` protocol.
